# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: smptp.gmail.com
    port: 587
    domain: gmail.com
    authentication: :login
    user_name: "redmine@gmail.com"
    password: "redmine"
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 587
    domain: gmail.com
    authentication: :login
    user_name: "redmine@gmail.com"
    password: "redmine"
