# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: smptp.gmail.com
    port: 587
    domain: gmail.com
    authentication: :login
    user_name: "redmine@gmail.com"
    password: "redmine"
    tls: true
